#!/usr/bin/env python

import MySQLdb as mysql
from google import search
from urllib2 import HTTPError
from sys import exit
from netifaces import AF_INET
import netifaces as ni
from time import time
from random import  randint
from os import system


DBUSER = ''
DBPASSWORD = ''
DBHOST = ''
DBPORT = 3306
DB = 'keywords'
DEBUG =  False


class Process():
    def __init__(self, ip):
        self.conn = mysql.connect(DBHOST,DBUSER, DBPASSWORD, DB, DBPORT)
        self.cursor = self.conn.cursor()
        self.ip = ip

    def __del__(self):
        self.cursor.close()

    def run(self):
        start = int(time())
        try:
            self.cursor.execute('UPDATE tasks SET status = 1, worker = %s WHERE status = 0 LIMIT 1', self.ip)
            self.conn.commit()
            self.cursor.execute('SELECT id, format, keyword, number FROM tasks WHERE status = 1 and worker = %s LIMIT 1', self.ip)
            self.conn.commit()
            p = self.cursor.fetchone()
            if DEBUG: print p[1]
            id, format, keyword, number = p
        except:
            # system('poweroff')
            pass

        numberOrig = number
        number = number + number * 0.15
        n = 0
        try:
            for url in search (keyword, stop = number, num = 100):
                if DEBUG: print url
                n += 1
                if n > number:
                    break
                self.cursor.execute('INSERT INTO url1 (format, keyword, url_num, url, keyword_id, worker) VALUES (%s, %s, %s, %s, %s, %s)', (format, keyword, n, url, id, self.ip))
                self.conn.commit()
        except HTTPError, e:
            print "Caught HTTP exception, %s" % e
            self.cursor.execute('DELETE FROM url1 WHERE keyword = %s;', keyword)
            self.cursor.execute('UPDATE tasks SET status = 0 WHERE id = %s;', id)
            self.cursor.execute('UPDATE agents SET status = 1 WHERE host = %s', self.ip)
            self.conn.commit()
            # system('poweroff')
        except:
            print "Caught exception" 
            self.cursor.execute('DELETE FROM url1 WHERE keyword = %s;', keyword)
            self.cursor.execute('UPDATE tasks SET status = 0 WHERE id = %s;', id)
            self.cursor.execute('UPDATE agents SET status = 1 WHERE host = %s', self.ip)
            self.conn.commit()
            # system('poweroff')

        if DEBUG: print "Finished"
        self.cursor.execute('UPDATE tasks SET status = 2, time = %s WHERE id = %s;', (int(time()) - start, id))
        self.cursor.execute('DELETE FROM url1 WHERE keyword = %s AND url_num > %s', (keyword, numberOrig))
        self.conn.commit()
        return 0


def main():
    ip = ni.ifaddresses('eth0')[AF_INET][0]['addr']
    ip = '{0}-{1}'.format(ip, randint(0, 99))
    scrape = Process(ip)
    while True:
        ret = scrape.run()


if __name__ == '__main__':
    main()
